//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProcesses
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileHdr
    {
        public FileHdr()
        {
            this.FileDtls = new HashSet<FileDtl>();
        }
    
        public int FileHdrId { get; set; }
        public int WOHdrID { get; set; }
        public string FileProduceTypeId { get; set; }
        public string FileDelimiterID { get; set; }
        public int ActivityID { get; set; }
        public short HeaderFieldCount { get; set; }
        public short PostingFieldCount { get; set; }
        public short TaxFieldCount { get; set; }
        public short ClearingFieldCount { get; set; }
        public short InterCompanyFieldCount { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual FileDelimiter FileDelimiter { get; set; }
        public virtual ICollection<FileDtl> FileDtls { get; set; }
        public virtual FileProduceType FileProduceType { get; set; }
    }
}
