//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProcesses
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileFieldType
    {
        public FileFieldType()
        {
            this.FileFields = new HashSet<FileField>();
        }
    
        public int UniqueFileFieldTypeId { get; set; }
        public string FileFieldlTypeId { get; set; }
        public string FileFieldDescription { get; set; }
    
        public virtual ICollection<FileField> FileFields { get; set; }
    }
}
