//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProcesses
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileField
    {
        public FileField()
        {
            this.FileDtls = new HashSet<FileDtl>();
        }
    
        public int FileFieldID { get; set; }
        public string FileFieldTypeID { get; set; }
        public string FileFieldName { get; set; }
        public string FieldFieldValue { get; set; }
    
        public virtual ICollection<FileDtl> FileDtls { get; set; }
        public virtual FileFieldType FileFieldType { get; set; }
    }
}
