//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProcesses
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDtl
    {
        public int FileDtlId { get; set; }
        public int FileHdrId { get; set; }
        public short FileFieldNo { get; set; }
        public int FileFieldId { get; set; }
    
        public virtual FileHdr FileHdr { get; set; }
        public virtual FileField FileField { get; set; }
    }
}
