//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProcesses
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptFile
    {
        public ScriptFile()
        {
            this.WorkOrderScriptHdrs = new HashSet<WorkOrderScriptHdr>();
        }
    
        public int ScriptFileID { get; set; }
        public string ScriptFileName { get; set; }
    
        public virtual ICollection<WorkOrderScriptHdr> WorkOrderScriptHdrs { get; set; }
    }
}
