//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProcesses
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPlanDtl
    {
        public TestPlanDtl()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int TestPlanDtlID { get; set; }
        public int TestPlanFileID { get; set; }
        public string Description { get; set; }
        public string LongDescription { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual TestPlanFile TestPlanFile { get; set; }
    }
}
