//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderCreator.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.WorkOrderDetails = new HashSet<WorkOrderDetail>();
        }
    
        public int ActivityID { get; set; }
        public string ActivityDescription { get; set; }
        public int ActivityTypeID { get; set; }
    
        public virtual ICollection<WorkOrderDetail> WorkOrderDetails { get; set; }
        public virtual ActivityType ActivityType { get; set; }
    }
}
