//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderCreator.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderDtlScript
    {
        public int WOScriptDtlID { get; set; }
        public int WODtlID { get; set; }
        public string FileName { get; set; }
    
        public virtual WorkOrderDetail WorkOrderDetail { get; set; }
    }
}
