//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderCreator.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkOrderLogEntities : DbContext
    {
        public WorkOrderLogEntities()
            : base("name=WorkOrderLogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> Clients { get; set; }
        public DbSet<WorkOrderHeader> WorkOrderHeaders { get; set; }
        public DbSet<Activity> Activities { get; set; }
        public DbSet<WorkOrderDetail> WorkOrderDetails { get; set; }
        public DbSet<ActivityType> ActivityTypes { get; set; }
        public DbSet<SourceScriptHdr> SourceScriptHdrs { get; set; }
        public DbSet<SourceScriptDtl> SourceScriptDtls { get; set; }
    }
}
